DEPOSIT = 1
WITHDRAWAL = 2
LOAN = 3
LOAN_PAID = 4
MONEY_TRANSFER = 5
MONEY_RECEIVED = 6

TRANSACTION_TYPE = (
    (DEPOSIT, 'Deposite'),
    (WITHDRAWAL, 'Withdrawal'),
    (LOAN, 'Loan'),
    (LOAN_PAID, 'Loan Paid'),
    (MONEY_TRANSFER, 'MONEY TRANSFER'),
    (MONEY_RECEIVED, 'MONEY RECEIVED'),
    
)