# Generated by Django 4.2.7 on 2024-05-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_remove_transfer_money_account_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transfer_to_account_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposite'), (2, 'Withdrawal'), (3, 'Loan'), (4, 'Loan Paid'), (5, 'MONEY TRANSFER'), (6, 'MONEY RECEIVED')], null=True),
        ),
        migrations.DeleteModel(
            name='Transfer_money',
        ),
    ]
